workflows:
  windows-build:
    name: Windows Build
    environment:
      vars:
        BUILD_TYPE: "Release"  # Тип сборки (Release/Debug)
    scripts:
      - name: Install Rust using Rustup
        script: |
          brew install rustup
          rustup default stable
          
      - name: Add Windows target
        script: |
          rustup target add x86_64-pc-windows-msvc
      - name: Build for Windows
        script: |
          cargo build --release --target x86_64-pc-windows-msvc
    artifacts:
      - target/x86_64-pc-windows-msvc/release/*.exe  # Артефакты (исполняемые файлы для Windows)